### PR TITLE
Add 'PayNim.app' to address book

### PR DESCRIPTION
**Pull request by paynimiqdev**
Hi,

I'd like to add address of my PayNim.app project.
This service allows to send NIM to email address, more info here:
https://www.reddit.com/r/Nimiq/comments/90qhtf/send_and_receive_nim_via_email_address_with/
or https://medium.com/@paynimiq/send-nimiq-cryptocurrency-to-email-address-via-paynim-app-10931a928e5c

https://www.paynim.app/

### CODE REVIEW

**Comment by sisou** [comment]
How does the app work? Is the user always sending to or receiving from this address? I thought you generate an address for each email sent? How are users interacting with this address?

**Comment by paynimiqdev** [comment]
@sisou it generates 'relay' address per each 'submit' button click.

So let's say you want to send some NIM to richy@nimiq.com
Then you need to go to https://www.paynim.app/ and set recipient email amount and click 'submit' button.
We will generate new 'relay' address to receive those NIM from you and will send you a Nimiq Safe link to load NIM to that address.
If you try to send NIM to Richy again we will generate new relay address.

Then we will move those NIMs from generated relay address to our operation address (address from the PR).

If richy@nimiq.com is not in our system yet then we will send him an email with instructions of how to create his own Nimiq address and withdraw those NIMs.
If richy@nimiq.com is already in our system and he has his own address associated with his email then we will send those NIMs from our operation address (address from the PR) to his personal address.

**So i'd like users to see `PayNim.app` sender address label if they received NIMs via paynim service.**

You can try it by yourself at https://www.paynim.app/ .
We are not going to store NIM on our operation address for a long time (unlike exchanges or tipbots).
The idea is to involve new users to create Nimiq address and withdraw NIMs as soon as possible.
If they won't do that within 7 days then we will send all NIMs back to the sender.

**Comment by sisou** [comment]
I understand. But that means your paragraph on your site about security is wrong, because there you state that you are *not* storing private keys or funds. But you just said that you are in fact holding the funds.

**Comment by paynimiqdev** [comment]
>But you just said that you are in fact holding the funds.

@sisou, technically you're right we're holding funds but just for new users if their email is not associated with their Nimiq address.
But if they associated their Nimiq address with their email address then we will send all funds to their personal address instantly.

So for new users we still need to hold on our operation address until they create their personal Nimiq address but for existing users we do hold - we just send to them instantly.

**Pull request merged**
